# Generated by Django 4.1.5 on 2023-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Açıklama'),
        ),
    ]
