# Generated by Django 4.1.5 on 2023-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_productimg_productstok_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstok',
            name='images',
            field=models.ManyToManyField(blank=True, to='appMy.productimg', verbose_name='Ürün Resimleri'),
        ),
    ]
