# Generated by Django 4.1.5 on 2023-04-07 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0007_alter_productstok_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopbasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_total', models.FloatField(default=0, verbose_name='Toplam Fiyat')),
                ('amount', models.IntegerField(default=0, verbose_name='Adet')),
                ('product_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.productstok', verbose_name='Sepetteki Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
