# Generated by Django 4.1.5 on 2023-04-12 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0010_alter_comment_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('image', models.FileField(upload_to=None, verbose_name='Resim')),
                ('job', models.CharField(max_length=50, verbose_name='İş')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
