# Generated by Django 4.1.5 on 2023-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Adres'),
        ),
    ]
