# Generated by Django 4.1.5 on 2023-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0015_alter_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(default='None/default.png', upload_to=None, verbose_name='Resim'),
        ),
    ]
